// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lmznksmxrcytpfzfcmlb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxtem5rc214cmN5dHBmemZjbWxiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyMjQxNDEsImV4cCI6MjA2ODgwMDE0MX0.Vvtry5TK1NR-jhyFpLmC-OFiI3ppksQyj62lbMZWHCc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});